[workspace]
resolver = "2"
members = [
  "crates/context-search",
  "crates/context-insert",
  "crates/context-read",
  "crates/context-trace",
  "crates/context-trace-macros",
  "tools/tracing-analyzer",
]
exclude = ["./crates/deps/petgraph", "./crates/deps/justlog"]

[profile.dev]
debug = true
opt-level = 0

[profile.release]
opt-level = 2 # fast and small wasm

[workspace.metadata.docs.rs]
no-deps = true
