[workspace]
resolver = "2"
members = [
  "crates/context-search",
  "crates/context-insert",
  "crates/context-read",
  "crates/context-trace",
  "crates/context-trace-macros",
  "tools/doc-viewer",
  "tools/log-viewer",
  "tools/viewer-api",
  "tools/tracing-analyzer",
  "tools/dungeon-crawler",
]
exclude = ["./crates/deps/petgraph", "./crates/deps/justlog"]

[profile.dev]
debug = true
opt-level = 0

[profile.release]
opt-level = 2 # fast and small wasm

[workspace.metadata.docs.rs]
no-deps = true
