
[workspace]
resolver = "2"
members = [
  "context-search",
  "context-insert",
  "context-read",
  "context-trace",
  "refactor-tool",
]
exclude = ["./tracing-egui", "./petgraph", "./minimal_options"]

[profile.dev]
debug = true
opt-level = 0

[profile.release]
opt-level = 2 # fast and small wasm
